import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../globals.css";
import { NextAuthProvider } from "@/auth/providers";
import { ThemeProvider } from "@/components/dark-mode/theme-provider";
import { SideBar } from "@/components/complex";
import Providers from "@/react-query/providers";
const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className={space.className}>
            <Providers>
              <main className="min-h-screen w-full flex flex-row gap-2 dark:bg-slate-700 pr-2 bg-slate-200">
                <SideBar />
                {children}
              </main>
            </Providers>
          </body>
        </ThemeProvider>
      </NextAuthProvider>
    </html>
  );
}
