export interface Job {
  JoborderId: number;
  JobTitle: string;
  Source: string;
  CompanyId: number;
  CompanyName: string;
  ContactId: number;
  ContactName: string;
  JoborderStatus: string;
  NumberOfJobs: number;
  StartImmediate: boolean;
  StartRelativePeriod: number | null;
  StartRelativeUnit: string | null;
  DurationPeriod: number | null;
  DurationUnit: string | null;
  SalaryUnit: string;
  SalaryRateLow: number | null;
  SalaryRateHigh: number | null;
  HoursPerWeek: number | null;
  DaysPerWeek: number | null;
  FeeRateType: string | null;
  FeeRate: number | null;
  FeeEstimatedTotal: number | null;
  LocationId: number | null;
  LocationName: string | null;
  WorkType: string;
  OwnerId: number;
  Owner: string;
  ConsultantId: string;
  Consultant: string;
  ConsultantId2: string | null;
  Consultant2: string | null;
  ConsultantId3: string | null;
  Consultant3: string | null;
  ConsultantId4: string | null;
  Consultant4: string | null;
  CreatedById: number;
  CreatedBy: string;
  CreatedAt: Date;
  UpdatedById: number;
  UpdatedBy: string;
  UpdatedAt: Date;
  ClosedById: number | null;
  ClosedBy: string | null;
  ClosedAt: Date | null;
  ClientCategory: string | null;
  BDaysOpen: number;
  JobAdderSource: string;
  JobCategory: string;
  JobSubCategory: string | null;
}
